[book]
authors = ["OBHQ"]
description = "The wiki for Obliteration"
language = "en"
multilingual = false
src = "src"

[rust]
edition = "2018"

[build]
build-dir = '/home/runner/work/obhqWebsite/temp/wiki/'
create-missing = true